/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package c1_presentacion;

import c1_presentacion.util.ConfiguradorDeTabla;
import c1_presentacion.util.Mensaje;
import c2_aplicacion.GestionarRegimenPensionarioServicio;
import c3_dominio.entidades.RegimenPensionario;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import mastersoft.modelo.ModeloTabla;
import mastersoft.tabladatos.Columna;
import mastersoft.tabladatos.Fila;
import mastersoft.tabladatos.Tabla;

/**
 *
 * @author EnriqueDavidJose
 */
public class FormGestionarRegimenPensionario extends javax.swing.JDialog {

    /**
     * Creates new form FormGestionarRegimenPensionario
     */
    public FormGestionarRegimenPensionario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Tabla tabla = new Tabla();
        tabla.agregarColumna(new Columna("ID", "java.lang.Integer"));
        tabla.agregarColumna(new Columna("Nombre", "java.lang.String"));
        ModeloTabla modeloTabla = new ModeloTabla(tabla);
        tablaRegimenPensionario.setModel(modeloTabla);  
    }

    private int obtenerId() {
        int numFila = tablaRegimenPensionario.getSelectedRow();
        if(numFila == -1){
            Mensaje.mostrarFilaNoSeleccionada(this);
            return 0;
        }
        ModeloTabla modeloTabla =(ModeloTabla)tablaRegimenPensionario.getModel();
        Fila fila = modeloTabla.obtenerFila(numFila);
        return (Integer)fila.obtenerCelda(0).getValor(); // se retorna el id de la fila seleccionada
    }

    private void buscar(){        
        Fila filaTabla;        
        String nombre = jTxtNombre.getText().trim();
        try {
            GestionarRegimenPensionarioServicio gestionarRegimenPensionarioServicio = new GestionarRegimenPensionarioServicio();
            List<RegimenPensionario> regimen = gestionarRegimenPensionarioServicio.buscarRegimenPensionario(nombre);
            ModeloTabla modeloTabla = (ModeloTabla)tablaRegimenPensionario.getModel();
            modeloTabla.eliminarTotalFilas();
            for(RegimenPensionario regimenPensionarios : regimen){
                filaTabla = new Fila();
                filaTabla.agregarValorCelda(regimenPensionarios.getRegimenpensionarioid());                
                filaTabla.agregarValorCelda(regimenPensionarios.getDescripcion());
                modeloTabla.agregarFila(filaTabla);
            }
            
            TableColumn columna0, columna1;
           
            columna0 = tablaRegimenPensionario.getColumnModel().getColumn(0);
            columna1 = tablaRegimenPensionario.getColumnModel().getColumn(1);
             columna0.setPreferredWidth(50);
            columna1.setPreferredWidth(500);
            columna1.setMaxWidth(400);
            columna1.setMinWidth(100);
            modeloTabla.refrescarDatos();
            
        } catch(Exception e){
            Mensaje.mostrarErrorDeConsulta(this);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        botCrear = new javax.swing.JButton();
        botModificar = new javax.swing.JButton();
        botSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        scrRegimenPensionario = new javax.swing.JScrollPane();
        tablaRegimenPensionario = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTxtNombre = new javax.swing.JTextField();
        botBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestionar Regimen Pensionario");

        jToolBar1.setRollover(true);

        botCrear.setText("Crear");
        botCrear.setFocusable(false);
        botCrear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botCrear.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCrearActionPerformed(evt);
            }
        });
        jToolBar1.add(botCrear);

        botModificar.setText("Modificar");
        botModificar.setFocusable(false);
        botModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botModificarActionPerformed(evt);
            }
        });
        jToolBar1.add(botModificar);

        botSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/c1_presentacion/resources/door_out.png"))); // NOI18N
        botSalir.setText("Salir");
        botSalir.setFocusable(false);
        botSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botSalirActionPerformed(evt);
            }
        });
        jToolBar1.add(botSalir);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        tablaRegimenPensionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaRegimenPensionario.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        scrRegimenPensionario.setViewportView(tablaRegimenPensionario);

        jLabel1.setText("Regimen Pensionario");

        botBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/c1_presentacion/resources/Find_16x16.png"))); // NOI18N
        botBuscar.setText("Buscar");
        botBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botBuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(scrRegimenPensionario, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrRegimenPensionario, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCrearActionPerformed
        // TODO add your handling code here:
        FormDatosRegimenPensionario formDatosRegimenPensionario = new FormDatosRegimenPensionario(this);
        formDatosRegimenPensionario.setVisible(true);
        buscar();
    }//GEN-LAST:event_botCrearActionPerformed

    private void botModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botModificarActionPerformed
        // TODO add your handling code here:
        int lectorid = obtenerId();
        if(lectorid == 0)
            return;
        GestionarRegimenPensionarioServicio gestionarRegimenPensionarioServicio = new GestionarRegimenPensionarioServicio();    
        try {
            //RegimenPensionario regimenPensionario = gestionarRegimenPensionarioServicio.buscar(obtenerId);   
             RegimenPensionario regimenPensionario = gestionarRegimenPensionarioServicio.buscarRegimenPensionario(lectorid);    
            if(regimenPensionario != null){
                FormDatosRegimenPensionario formDatosLector = new FormDatosRegimenPensionario(this, regimenPensionario);
                formDatosLector.setVisible(true);
            }
            else
                Mensaje.mostrarFilaNoExiste(this);
            buscar();
        } catch(Exception e){
            Mensaje.mostrarErrorDeConsulta(this);
        }   
    }//GEN-LAST:event_botModificarActionPerformed

    private void botBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botBuscarActionPerformed
        // TODO add your handling code here:
        buscar();
    }//GEN-LAST:event_botBuscarActionPerformed

    private void botSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botBuscar;
    private javax.swing.JButton botCrear;
    private javax.swing.JButton botModificar;
    private javax.swing.JButton botSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField jTxtNombre;
    private javax.swing.JScrollPane scrRegimenPensionario;
    private javax.swing.JTable tablaRegimenPensionario;
    // End of variables declaration//GEN-END:variables
}
