/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package c1_presentacion;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Administrador
 */
public class FormMenu extends javax.swing.JFrame {

    /**
     * Creates new form FormMenu
     */
    public FormMenu() {
        asignarLookandfeel();
        setExtendedState(MAXIMIZED_BOTH);
        initComponents();
    }
    
    private void asignarLookandfeel(){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuGestionarEmpleado = new javax.swing.JMenuItem();
        menuGestionarAfiliacionRegimenPensionario = new javax.swing.JMenuItem();
        menuGestionarContrato = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuGestionarTipoDocumento = new javax.swing.JMenuItem();
        menuGestionarNivelEducacion = new javax.swing.JMenuItem();
        menuGestionarTipoEmpleado = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuGestionarNacionalidad = new javax.swing.JMenuItem();
        menuGestionarUbigeo = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menuGestionarDepartamento = new javax.swing.JMenuItem();
        menuGestionarCargos = new javax.swing.JMenuItem();
        menuGestionarCentroCosto = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuGestionarRegimenPensionario = new javax.swing.JMenuItem();
        menuGestionarTipoDeRegimen = new javax.swing.JMenuItem();
        menuGestionarPeriodo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuProcesarCalculoPlanilla = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mnuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Planilla - EV-Soft S.A.C. v.1.0.0.0");

        jMenu1.setText("Administración");

        mnuGestionarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/c1_presentacion/resources/Employee_16x16.png"))); // NOI18N
        mnuGestionarEmpleado.setText("Gestionar Empleado");
        mnuGestionarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGestionarEmpleadoActionPerformed(evt);
            }
        });
        jMenu1.add(mnuGestionarEmpleado);

        menuGestionarAfiliacionRegimenPensionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/c1_presentacion/resources/BOContact2_16x16.png"))); // NOI18N
        menuGestionarAfiliacionRegimenPensionario.setText("Gestionar Afiliacion Regimen Pensionario");
        menuGestionarAfiliacionRegimenPensionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestionarAfiliacionRegimenPensionarioActionPerformed(evt);
            }
        });
        jMenu1.add(menuGestionarAfiliacionRegimenPensionario);

        menuGestionarContrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/c1_presentacion/resources/BONote_16x16.png"))); // NOI18N
        menuGestionarContrato.setText("Gestionar Contrato");
        menuGestionarContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestionarContratoActionPerformed(evt);
            }
        });
        jMenu1.add(menuGestionarContrato);
        jMenu1.add(jSeparator1);

        menuGestionarTipoDocumento.setText("Gestionar Tipo Documento");
        jMenu1.add(menuGestionarTipoDocumento);

        menuGestionarNivelEducacion.setText("Gestionar Nivel Educacion");
        jMenu1.add(menuGestionarNivelEducacion);

        menuGestionarTipoEmpleado.setText("Gestionar Tipo Empleado");
        jMenu1.add(menuGestionarTipoEmpleado);
        jMenu1.add(jSeparator2);

        menuGestionarNacionalidad.setText("Gestionar Nacionalidad");
        jMenu1.add(menuGestionarNacionalidad);

        menuGestionarUbigeo.setText("Gestionar Ubigeo");
        jMenu1.add(menuGestionarUbigeo);
        jMenu1.add(jSeparator4);

        menuGestionarDepartamento.setText("Gestionar Departamento");
        menuGestionarDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestionarDepartamentoActionPerformed(evt);
            }
        });
        jMenu1.add(menuGestionarDepartamento);

        menuGestionarCargos.setText("Gestionar Cargo");
        jMenu1.add(menuGestionarCargos);

        menuGestionarCentroCosto.setText("Gestionar Centro de Costos");
        jMenu1.add(menuGestionarCentroCosto);
        jMenu1.add(jSeparator3);

        menuGestionarRegimenPensionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/c1_presentacion/resources/GroupByResource_16x16.png"))); // NOI18N
        menuGestionarRegimenPensionario.setText("Gestionar Regimen Pensionario");
        menuGestionarRegimenPensionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestionarRegimenPensionarioActionPerformed(evt);
            }
        });
        jMenu1.add(menuGestionarRegimenPensionario);

        menuGestionarTipoDeRegimen.setText("Gestionar Tipo de Regimen");
        jMenu1.add(menuGestionarTipoDeRegimen);

        menuGestionarPeriodo.setText("Gestionar Periodo");
        jMenu1.add(menuGestionarPeriodo);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Procesos");

        menuProcesarCalculoPlanilla.setText("Procesar Calculo Planilla");
        menuProcesarCalculoPlanilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProcesarCalculoPlanillaActionPerformed(evt);
            }
        });
        jMenu2.add(menuProcesarCalculoPlanilla);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Aplicación");

        jMenuItem1.setText("Ayuda");
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("Acerca de");
        jMenu3.add(jMenuItem2);
        jMenu3.add(jSeparator5);

        mnuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/c1_presentacion/resources/door_out.png"))); // NOI18N
        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        jMenu3.add(mnuSalir);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuGestionarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGestionarEmpleadoActionPerformed

        // TODO add your handling code here:
        FormGestionarEmpleado formGestionarEmpleado = new FormGestionarEmpleado(this, true);
//        //este metodo devuelve el tamaño de la pantalla
//        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
//        //obtenemos el tamaño de la ventana
//        Dimension ventana = formGestionarEmpleado.getSize();
//        //para centrar la ventana lo hacemos con el siguiente calculo
//        formGestionarEmpleado.setLocation((pantalla.width - ventana.width) / 2, (pantalla.height - ventana.height) / 2);
//        jPanel.add(formGestionarEmpleado);
        formGestionarEmpleado.setVisible(true);

    }//GEN-LAST:event_mnuGestionarEmpleadoActionPerformed

    private void menuGestionarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestionarDepartamentoActionPerformed
        // TODO add your handling code here:
        FormGestionarDepartamento formGestionarDepartamento = new FormGestionarDepartamento(this, true);
        formGestionarDepartamento.setVisible(true);
    }//GEN-LAST:event_menuGestionarDepartamentoActionPerformed

    private void menuGestionarRegimenPensionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestionarRegimenPensionarioActionPerformed
        // TODO add your handling code here:
        FormGestionarRegimenPensionario formGestionarRegimenPensionario = new FormGestionarRegimenPensionario(this, true);
        formGestionarRegimenPensionario.setVisible(true);
    }//GEN-LAST:event_menuGestionarRegimenPensionarioActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void menuGestionarAfiliacionRegimenPensionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestionarAfiliacionRegimenPensionarioActionPerformed
        // TODO add your handling code here:
        FormGestionarAfiliacionRegimenPensionario formGestionarAfiliacionRegimenPensionario =  new FormGestionarAfiliacionRegimenPensionario(this,true);
        formGestionarAfiliacionRegimenPensionario.setVisible(true);
    }//GEN-LAST:event_menuGestionarAfiliacionRegimenPensionarioActionPerformed

    private void menuGestionarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestionarContratoActionPerformed
        // TODO add your handling code here:
        FormGestionarContrato formGestionarContrato =  new FormGestionarContrato(this, true);
        formGestionarContrato.setVisible(true);
    }//GEN-LAST:event_menuGestionarContratoActionPerformed

    private void menuProcesarCalculoPlanillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProcesarCalculoPlanillaActionPerformed
        // TODO add your handling code here:
        FormProcesarPlanilla formProcesarPlanilla =  new FormProcesarPlanilla(this, true);
        formProcesarPlanilla.setVisible(true);
    }//GEN-LAST:event_menuProcesarCalculoPlanillaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JMenuItem menuGestionarAfiliacionRegimenPensionario;
    private javax.swing.JMenuItem menuGestionarCargos;
    private javax.swing.JMenuItem menuGestionarCentroCosto;
    private javax.swing.JMenuItem menuGestionarContrato;
    private javax.swing.JMenuItem menuGestionarDepartamento;
    private javax.swing.JMenuItem menuGestionarNacionalidad;
    private javax.swing.JMenuItem menuGestionarNivelEducacion;
    private javax.swing.JMenuItem menuGestionarPeriodo;
    private javax.swing.JMenuItem menuGestionarRegimenPensionario;
    private javax.swing.JMenuItem menuGestionarTipoDeRegimen;
    private javax.swing.JMenuItem menuGestionarTipoDocumento;
    private javax.swing.JMenuItem menuGestionarTipoEmpleado;
    private javax.swing.JMenuItem menuGestionarUbigeo;
    private javax.swing.JMenuItem menuProcesarCalculoPlanilla;
    private javax.swing.JMenuItem mnuGestionarEmpleado;
    private javax.swing.JMenuItem mnuSalir;
    // End of variables declaration//GEN-END:variables
}
