/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package c1_presentacion;

import c1_presentacion.util.Funciones;
import c1_presentacion.util.Mensaje;
import c2_aplicacion.GestionarAfiliacionRegimenPensionarioServicio;
import c2_aplicacion.GestionarEmpleadoServicio;
import c2_aplicacion.GestionarRegimenPensionarioServicio;
import c2_aplicacion.GestionarTipoDocumentoServicio;
import c3_dominio.entidades.AfiliacionRegimenPensionario;
import c3_dominio.entidades.Banda;
import c3_dominio.entidades.Contrato;
import c3_dominio.entidades.Empleado;
import c3_dominio.entidades.RegimenPensionario;
import c3_dominio.entidades.TipoDocumento;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class FormGestionarAfiliacionRegimenPensionario extends javax.swing.JDialog {

    private AfiliacionRegimenPensionario afiliacionRegimenPensionario;
    private Empleado empleado;
    private RegimenPensionario regimenPensionario;
    
    private List<TipoDocumento> tipodocumentos;
    private List<RegimenPensionario> regimenPensionarios;
    /**
     * Creates new form FormGestionarAfiliacionRegimenPensionario
     */
    public FormGestionarAfiliacionRegimenPensionario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        llenaComboTipoDocumento(this.jCboTipDocu);
        llenaComboRegimenPensionario(this.jCboRegimenPensionario);
        
        //Instanciomos
        this.afiliacionRegimenPensionario = new AfiliacionRegimenPensionario();
    }

    private void activarBotonBuscar(){
        if(empleado != null) //&& ejemplar != null)
            botBuscar.setEnabled(true);
    }
    
    private void llenaComboTipoDocumento(javax.swing.JComboBox jComboBox) {      
        DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
        jComboBox.removeAllItems();

        GestionarTipoDocumentoServicio gestionarTipoDocumentoServicio = new GestionarTipoDocumentoServicio();
        try {
            tipodocumentos = gestionarTipoDocumentoServicio.cargarTipoDocumento();
        
            for(TipoDocumento tipodocumento : tipodocumentos){
                modeloCombo.addElement(new Banda(tipodocumento.getDescripcion(),tipodocumento.getTipodocumentoid()));
            }
            jComboBox.setModel(modeloCombo);
            
        } catch (Exception e) {
            Mensaje.mostrarErrorDeConsulta(this);
        }
    }
    
    private void llenaComboRegimenPensionario(javax.swing.JComboBox jComboBox) {      
        DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
        jComboBox.removeAllItems();

        GestionarRegimenPensionarioServicio gestionarRegimenPensionarioServicio = new GestionarRegimenPensionarioServicio();
        try {
            regimenPensionarios = gestionarRegimenPensionarioServicio.cargarRegimenPensionario();
        
            for(RegimenPensionario regimenPensionario : regimenPensionarios){
                modeloCombo.addElement(new Banda(regimenPensionario.getDescripcion(),regimenPensionario.getRegimenpensionarioid()));
            }
            jComboBox.setModel(modeloCombo);
            
        } catch (Exception e) {
            Mensaje.mostrarErrorDeConsulta(this);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        botAfiliacion = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCboTipDocu = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jTxtNumero = new javax.swing.JTextField();
        botBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLblEmpleado = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jDtChsFecAfi = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jTxtCussp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jCboRegimenPensionario = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jCboTipoRegimen = new javax.swing.JComboBox();
        botGrabar = new javax.swing.JButton();
        botCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Afiliación Regimen Pensionario");

        jToolBar1.setRollover(true);

        botAfiliacion.setText("Nueva Afiliacion");
        botAfiliacion.setFocusable(false);
        botAfiliacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botAfiliacion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botAfiliacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAfiliacionActionPerformed(evt);
            }
        });
        jToolBar1.add(botAfiliacion);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Afiliación Regimen Pensionario"));

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Empleado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 51, 0))); // NOI18N

        jLabel1.setText("Tipo Documento");

        jLabel2.setText("Numero");

        botBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/c1_presentacion/resources/Find_16x16.png"))); // NOI18N
        botBuscar.setText("Buscar");
        botBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botBuscarActionPerformed(evt);
            }
        });

        jLabel3.setText("Empleado");

        jLblEmpleado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblEmpleado.setForeground(new java.awt.Color(102, 0, 0));
        jLblEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLblEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCboTipDocu, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botBuscar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jCboTipDocu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLblEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel5.setText("Fecha Afiliacion");

        jLabel6.setText("Nro. CUSSP");

        jLabel7.setText("Regimen Pensionario");

        jLabel8.setText("Tipo Regimen");

        jCboTipoRegimen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Comision Flujo", "Comision Mixta" }));

        botGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/c1_presentacion/resources/Save_16x16.png"))); // NOI18N
        botGrabar.setText("Guardar");
        botGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botGrabarActionPerformed(evt);
            }
        });

        botCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/c1_presentacion/resources/Cancel_16x16.png"))); // NOI18N
        botCancelar.setText("Cancelar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(484, 484, 484)
                        .addComponent(botGrabar)
                        .addGap(18, 18, 18)
                        .addComponent(botCancelar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jDtChsFecAfi, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtCussp, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCboRegimenPensionario, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCboTipoRegimen, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jDtChsFecAfi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTxtCussp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jCboRegimenPensionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCboTipoRegimen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botGrabar)
                    .addComponent(botCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botAfiliacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAfiliacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botAfiliacionActionPerformed

    private void botBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botBuscarActionPerformed
        // TODO add your handling code here:
        try {
            GestionarEmpleadoServicio gestionarEmpleadoServicio = new GestionarEmpleadoServicio();
                    
            empleado = gestionarEmpleadoServicio.buscarEmpleado(Funciones.codIntCombo(this.jCboTipDocu), this.jTxtNumero.getText());
            if(empleado != null)
                this.jLblEmpleado.setText(empleado.getApellidopaterno() + " " + empleado.getApellidomaterno() + ", " + empleado.getNombre());
            else
                Mensaje.mostrarAdvertencia(this, "El empleado no se encuentra registrado");
                activarBotonBuscar();
        } catch (Exception e) {
            Mensaje.mostrarErrorDeConsulta(this);
        }
        
    }//GEN-LAST:event_botBuscarActionPerformed

    private void botGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botGrabarActionPerformed
        // TODO add your handling code here:
        int registros_afectados;
        try {
            afiliacionRegimenPensionario.setEmpleado(empleado); //empleado ya lo tengo desde la busqueda.
            afiliacionRegimenPensionario.setFechaafiliacion(this.jDtChsFecAfi.getDate());
            afiliacionRegimenPensionario.setNumerocuspp(this.jTxtCussp.getText());
            
            GestionarRegimenPensionarioServicio gestionarRegimenPensionarioServicio =  new GestionarRegimenPensionarioServicio();
            regimenPensionario = gestionarRegimenPensionarioServicio.buscarRegimenPensionario(Funciones.codIntCombo(this.jCboRegimenPensionario));
            afiliacionRegimenPensionario.setRegimenpensionario(regimenPensionario);
            
            afiliacionRegimenPensionario.setTipocomision((String) this.jCboTipoRegimen.getSelectedItem());
            
            GestionarAfiliacionRegimenPensionarioServicio gestionarAfiliacionRegimenPensionarioServicio = new GestionarAfiliacionRegimenPensionarioServicio();
            
            if (empleado.tieneAsignacionFamiliar()==true)
                JOptionPane.showMessageDialog(this,"Empleado ya esta Afiliado.","EV-Soft: Advertencia",JOptionPane.WARNING_MESSAGE);
            else{
                registros_afectados = gestionarAfiliacionRegimenPensionarioServicio.crearAfiliacionRegimenPensionario(afiliacionRegimenPensionario);

                if (registros_afectados==1){
                    Mensaje.mostrarAfirmacionDeCreacion(this);
                    //inicializarEmpleado();
                }
                else
                    Mensaje.mostrarAdvertenciaDeCreacion(this);
            }
        } catch (Exception e) {
            Mensaje.mostrarError(this, e.getMessage());
        }
    }//GEN-LAST:event_botGrabarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botAfiliacion;
    private javax.swing.JButton botBuscar;
    private javax.swing.JButton botCancelar;
    private javax.swing.JButton botGrabar;
    private javax.swing.JComboBox jCboRegimenPensionario;
    private javax.swing.JComboBox jCboTipDocu;
    private javax.swing.JComboBox jCboTipoRegimen;
    private com.toedter.calendar.JDateChooser jDtChsFecAfi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLblEmpleado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField jTxtCussp;
    private javax.swing.JTextField jTxtNumero;
    // End of variables declaration//GEN-END:variables
}
