/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package c1_presentacion;

import c1_presentacion.util.Formateador;
import c1_presentacion.util.Mensaje;
import c1_presentacion.util.ValidadorDeDatosDeEntrada;
import c2_aplicacion.GestionarRegimenPensionarioServicio;
import c3_dominio.entidades.RegimenPensionario;
import static c3_dominio.entidades.RegimenPensionario.datosObligatorios;
import java.util.ArrayList;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Administrador
 */
public class FormDatosRegimenPensionario extends javax.swing.JDialog {

    private RegimenPensionario regimenPensionario;
    private final int ACCION_CREAR = 1;
    private final int ACCION_MODIFICAR = 2;
    private int tipo_accion;
    
    private ArrayList<String> datosObligatorios;
    private ArrayList<String> datosUnicos;
    private ArrayList<JComponent> listaDeDatosDeEntrada;
    private ArrayList<JLabel> listaDeEtiquetas;    
    private ArrayList<JTextField> listaDeDatosInvalidos;
    
    /**
     * Creates new form FormDatosRegimenPensionario
     */
    public FormDatosRegimenPensionario(JDialog owner) {
        super(owner, true);
        initComponents();
        //inicializarCamposDeValidacion();
        //pintarDatosObligatoriosYUnicos();
       // ValidadorDeDatosDeEntrada.validarActivacionDeBotonDeComando(listaDeDatosDeEntrada, datosObligatorios, listaDeDatosInvalidos.size(), botGuardar);
        //etiFechaSancion.setVisible(false);
        //txtFechaSancion.setVisible(false);
        //etiFormato.setVisible(false);                
        tipo_accion = ACCION_CREAR;
        this.regimenPensionario = new RegimenPensionario();
    }
    
    public FormDatosRegimenPensionario(JDialog owner, RegimenPensionario regimenPensionario) {
        super(owner, true);
        initComponents();
        inicializarCamposDeValidacion();
        pintarDatosObligatoriosYUnicos();        
        tipo_accion = ACCION_MODIFICAR;
        this.regimenPensionario = regimenPensionario;
       // txtNombre.setText(lector.getNombre());
        //txtDni.setText(lector.getDni());
        //txtDireccion.setText(lector.getDireccion());
        //SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
        //if(lector.getFechapenalizada()!=null)
        //    txtFechaSancion.setText(formatoFecha.format(lector.getFechapenalizada()));
        //txtCorreo.setText(lector.getCorreoe());
    }

    private void inicializarCamposDeValidacion(){
        datosObligatorios = RegimenPensionario.datosObligatorios();
        datosUnicos = RegimenPensionario.datosUnicos();
        listaDeDatosInvalidos = new ArrayList<>();
        listaDeDatosDeEntrada = new ArrayList<>();
        listaDeEtiquetas = new ArrayList<>();
        listaDeDatosDeEntrada.add(this.jTxtRegimenPensionario);
        listaDeEtiquetas.add(this.jLabel2);     
    }
    
    private void pintarDatosObligatoriosYUnicos() {
        Formateador.pintarComponentesDeEntradaObligatoria(listaDeDatosDeEntrada, datosObligatorios);
        Formateador.pintarEtiquetasDeValorUnico(listaDeEtiquetas, datosUnicos);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtRegimenPensionario = new javax.swing.JTextField();
        botGrabar = new javax.swing.JButton();
        botCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrando datos...");

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("Registro de Regimen Pensionario");

        jLabel2.setText("Regimen Pensionario");

        jTxtRegimenPensionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtRegimenPensionarioKeyReleased(evt);
            }
        });

        botGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/c1_presentacion/resources/Save_16x16.png"))); // NOI18N
        botGrabar.setText("Grabar");
        botGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botGrabarActionPerformed(evt);
            }
        });

        botCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/c1_presentacion/resources/Cancel_16x16.png"))); // NOI18N
        botCancelar.setText("Cancelar");
        botCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTxtRegimenPensionario, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(botGrabar)
                        .addGap(44, 44, 44)
                        .addComponent(botCancelar)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtRegimenPensionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botGrabar)
                    .addComponent(botCancelar))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botGrabarActionPerformed
        // TODO add your handling code here:
        regimenPensionario.setDescripcion(jTxtRegimenPensionario.getText());
//        lector.setDni(txtDni.getText());
//        lector.setDireccion(txtDireccion.getText());
////        lector.setCorreoe(txtCorreo.getText());
//        if(tipo_accion == ACCION_MODIFICAR && !txtFechaSancion.getText().trim().isEmpty())          
//            lector.setFechapenalizadaDeValor(LocalDate.parse(txtFechaSancion.getText()));
//        else
//            lector.setFechapenalizada(null);                         
        GestionarRegimenPensionarioServicio gestionarRegimenPensionarioServicio = new GestionarRegimenPensionarioServicio();
        int registros_afectados;
        if(tipo_accion == ACCION_CREAR){
            try{
                registros_afectados = gestionarRegimenPensionarioServicio.crearRegimenPensionario(regimenPensionario);   
                if(registros_afectados == 1){
                    Mensaje.mostrarAfirmacionDeCreacion(this);
                    this.dispose(); // se cierra la ventana
                }
                else
                    Mensaje.mostrarAdvertenciaDeCreacion(this);
            }
            catch(Exception e){
                Mensaje.mostrarErrorDeCreacion(this);
            }               
        }        
        else{
            try{
                registros_afectados = gestionarRegimenPensionarioServicio.modificarRegimenPensionario(regimenPensionario);   
                if(registros_afectados == 1){
                    Mensaje.mostrarAfirmacionDeActualizacion(this);
                    this.dispose(); // se cierra la ventana
                }
                else
                    Mensaje.mostrarAdvertenciaDeActualizacion(this);
            }
            catch(Exception e){
                Mensaje.mostrarErrorDeActualizacion(this);
            }            
        }
    }//GEN-LAST:event_botGrabarActionPerformed

    private void botCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botCancelarActionPerformed

    private void jTxtRegimenPensionarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtRegimenPensionarioKeyReleased
        // TODO add your handling code here:
        boolean esDatoObligatorio = datosObligatorios.contains(jTxtRegimenPensionario.getName());
        
        ValidadorDeDatosDeEntrada.validarActivacionDeBotonDeComando(listaDeDatosDeEntrada, datosObligatorios, listaDeDatosInvalidos.size(), botGrabar);
    }//GEN-LAST:event_jTxtRegimenPensionarioKeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
        jTxtRegimenPensionario.requestFocusInWindow();
    } 
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botCancelar;
    private javax.swing.JButton botGrabar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtRegimenPensionario;
    // End of variables declaration//GEN-END:variables
}
